# Generated by Django 5.2.15 on 2026-06-24 10:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HouseType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('name', models.CharField(blank=True, choices=[('cabin', 'Cabin'), ('tiny house', 'Tiny House'), ('a frame', 'A Frame'), ('yurt', 'Yurt'), ('Treehouse', 'treehouse'), ('Boat', 'boat')], null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
