# Generated by Django 5.2.15 on 2026-06-24 10:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('title', models.CharField(max_length=20, verbose_name='Заголовок тура')),
                ('numb_people', models.TextField(verbose_name='Кол-во людей')),
                ('image', models.ImageField(upload_to='tours/images/')),
                ('slug', models.SlugField(unique=True)),
                ('real_price', models.FloatField(verbose_name='Реальная цена')),
                ('discount_price', models.FloatField(verbose_name='Скидочная цена')),
                ('stars_number', models.IntegerField(verbose_name='Кол-во звезд')),
                ('house_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.housetype', verbose_name='Тип помещения')),
            ],
            options={
                'verbose_name': 'Тур',
                'verbose_name_plural': 'Туры',
            },
        ),
    ]
