# Generated by Django 5.2.15 on 2026-06-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_tour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='discount_price',
        ),
        migrations.AddField(
            model_name='tour',
            name='discount_percent',
            field=models.FloatField(null=True, verbose_name='Скидочная процент'),
        ),
    ]
