# Generated by Django 5.2.15 on 2026-06-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_remove_tour_discount_price_tour_discount_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='discount_percent',
            field=models.IntegerField(null=True, verbose_name='Скидочная процент'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='real_price',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Реальная цена'),
        ),
    ]
