# Generated by Django 5.2.15 on 2026-06-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_alter_tour_discount_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='discount_percent',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True, verbose_name='Скидочная процент'),
        ),
    ]
