# Generated by Django 5.2.15 on 2026-06-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_alter_tour_discount_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='real_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Реальная цена'),
        ),
    ]
