# Generated by Django 5.2.15 on 2026-06-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_alter_tour_real_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='discount_percent',
            field=models.IntegerField(null=True, verbose_name='Скидочная процент'),
        ),
    ]
