# Generated by Django 5.2.15 on 2026-06-24 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0008_alter_tour_discount_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='housetype',
            name='slug',
            field=models.SlugField(null=True, unique=True, verbose_name='Ссылка для типа дома'),
        ),
    ]
