# Generated by Django 5.2.15 on 2026-06-25 07:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0010_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesTour',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('image', models.ImageField(upload_to='images/tours/', verbose_name='Фото туров')),
            ],
            options={
                'verbose_name': 'Фото туров',
            },
        ),
        migrations.AlterField(
            model_name='tour',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tours.imagestour', verbose_name='Фото туров'),
        ),
    ]
