# Generated by Django 5.2.15 on 2026-06-25 08:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0012_remove_tour_image_imagestour_tour'),
    ]

    operations = [
        migrations.CreateModel(
            name='Highlights',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('text', models.TextField()),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.tour', verbose_name='Преимущества')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Overview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('text', models.TextField(verbose_name='Описание')),
                ('duration', models.CharField(max_length=30, verbose_name='Продолжительность тура')),
                ('tour_type', models.CharField(max_length=40, verbose_name='Тип тура')),
                ('language', models.CharField(max_length=30, verbose_name='Язык тура')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='обзор', to='tours.tour')),
            ],
            options={
                'verbose_name': 'Оюзор тура',
            },
        ),
    ]
