# Generated by Django 5.2.15 on 2026-06-25 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0013_highlights_overview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlights',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='tours.tour', verbose_name='Преимущества'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overview', to='tours.tour'),
        ),
    ]
