# Generated by Django 5.2.15 on 2026-06-25 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0014_alter_highlights_tour_alter_overview_tour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlights',
            name='tour',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='tours.tour', verbose_name='Преимущества'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='tour',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='overview', to='tours.tour'),
        ),
    ]
