# Generated by Django 5.2.15 on 2026-06-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0017_alter_faq_id_alter_highlights_id_alter_housetype_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='away_country',
            field=models.CharField(max_length=30, null=True, verbose_name='Гостевая страна'),
        ),
        migrations.AddField(
            model_name='tour',
            name='home_country',
            field=models.CharField(max_length=30, null=True, verbose_name='Страна вылета'),
        ),
    ]
