# Generated by Django 5.2.15 on 2026-07-05 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0018_tour_away_country_tour_home_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housetype',
            name='name',
            field=models.CharField(blank=True, choices=[('cabin', 'Cabin'), ('tiny house', 'Tiny House'), ('a frame', 'A Frame'), ('yurt', 'Yurt'), ('Treehouse', 'treehouse'), ('Boat', 'boat')], max_length=60, null=True),
        ),
    ]
