# Generated by Django 5.2.15 on 2026-06-23 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
