# Generated by Django 5.2.15 on 2026-06-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_article_id_alter_blogcomment_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_user', models.CharField(max_length=50, verbose_name='IP посетителя')),
            ],
            options={
                'verbose_name': 'IP',
                'verbose_name_plural': 'Ips',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='views',
            field=models.ManyToManyField(blank=True, null=True, to='blog.ipuser', verbose_name='Просмотры API'),
        ),
    ]
