# Generated by Django 5.2.15 on 2026-06-19 18:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingBenefits',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('image', models.ImageField(upload_to='main/images/booking/', verbose_name='Фото пользы туров')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Польза туров',
                'verbose_name_plural': 'Пользы туров',
            },
        ),
        migrations.CreateModel(
            name='ClientReviews',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('author_img', models.ImageField(blank=True, null=True, upload_to='img/author/', verbose_name='Фото комментария')),
                ('work_type', models.CharField(max_length=20, verbose_name='Занятие автора')),
                ('review_text', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecommendedPackages',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('title', models.CharField(max_length=30, verbose_name='Название рекомендуемого тура')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/recommended')),
                ('destination', models.CharField(max_length=20, verbose_name='Место отдыха')),
                ('country', models.CharField(max_length=10, verbose_name='Страна')),
                ('price', models.IntegerField(verbose_name='Рекомедуемая цена')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
