# Generated by Django 5.2.15 on 2026-06-19 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientreviews',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='recommendedpackages',
            options={'verbose_name': 'Рекоммендуемый тур', 'verbose_name_plural': 'Рекоммендуемые туры'},
        ),
    ]
