# Generated by Django 5.2.15 on 2026-06-19 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_clientreviews_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientreviews',
            name='name',
            field=models.CharField(max_length=20, null=True, verbose_name='Имя пользователя'),
        ),
    ]
