# Generated by Django 5.2.15 on 2026-06-20 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_clientreviews_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingbenefits',
            name='title',
            field=models.CharField(max_length=10, null=True, verbose_name='Название пользы туров'),
        ),
    ]
