# Generated by Django 5.2.15 on 2026-06-20 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_bookingbenefits_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingbenefits',
            name='title',
            field=models.CharField(max_length=20, null=True, verbose_name='Название пользы туров'),
        ),
    ]
